language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install python-numpy python-scipy python-matplotlib python-qt4 python-h5py
#   - sudo apt-get install libhdf5-openmpi-dev
#   - cd ..
#   - wget http://sourceforge.net/projects/pyqt/files/sip/sip-4.14.5/sip-4.14.5.tar.gz
#   - tar -xvf sip-4.14.5.tar.gz
#   - cd sip-4.14.5
#   - python configure.py
#   - make -j 4
#   - sudo make install
#   - cd ..
#   - wget http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.10/PyQt-x11-gpl-4.10.tar.gz
#   - tar -xvf PyQt-x11-gpl-4.10.tar.gz
#   - cd PyQt-x11-gpl-4.10
#   - python configure.py --confirm-license
#   - make -j 4
#   - sudo make install
#   - cd ../quicknxs
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: 
#   - 'if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install http://sourceforge.net/projects/pyparsing/files/pyparsing/pyparsing-1.5.7/pyparsing-1.5.7.tar.gz; fi'
#   - "pip install numpy --use-mirrors"
#   - "export C_INCLUDE_PATH=/usr/lib/openmpi/include"
#   - "pip install h5py --use-mirrors"
# #  - "pip install scipy --use-mirrors"
  - "pip install matplotlib --use-mirrors"
  - 'if [ $TRAVIS_PYTHON_VERSION == "3.2" ]; then 2to3 -w quicknxs quick_nxs; fi'
# command to run tests
script: python -m unittest test_all
