language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
before_install:
  - sudo  apt-get install libicu-dev libphonon-dev libqtassistantclient-dev libdbus-1-dev swig sharutils libblas-dev
install: 
  - 'if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install http://sourceforge.net/projects/pyparsing/files/pyparsing/pyparsing-1.5.7/pyparsing-1.5.7.tar.gz; fi'
  - "pip install numpy --use-mirrors"
#  - "pip install scipy --use-mirrors"
  - "pip install matplotlib --use-mirrors"
  - "pip install sip --use-mirrors"
  - "pip install pyqt4 --use-mirrors"
# command to run tests
script: python test_all.py
